name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draft:
    name: Drafter
    uses: TheDragonCode/.github/.github/workflows/release-drafter.yml@main

  build:
    needs: draft

    name: App
    if: ${{ needs.check.outputs.allow }} == 1
    uses: TheDragonCode/github-notifications/.github/workflows/build.yml@main
    with:
      tag: ${{ needs.draft.outputs.tag_name }}
      token: ${{ secrets.COMPOSER_TOKEN }}
