name: Release Drafter

on:
  push:
    branches:
      - main
      - 1.x
  workflow_dispatch:

jobs:
  draft:
    name: Drafter
    uses: TheDragonCode/.github/.github/workflows/release-drafter.yml@main

  build:
    needs: draft

    name: Application
    uses: TheDragonCode/github-notifications/.github/workflows/build.yml@1.x
    with:
      tag: ${{ needs.draft.outputs.tag_name }}
